[package]
name = "grpc-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

build = "build.rs"

[dependencies]
prost = "0.12.6"
tonic = "0.11.0"

[build-dependencies]
tonic-build = "0.11.0"
